apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    config_items:
    - repos:
      - ascend
      excluded_repos:
      - ascend/pytorch
      - ascend/AscendSpeed
      - ascend/AscendSpeed2
      - ascend/ModelLink
      - ascend/ads